### ISSUE TITLE
web协议和app协议不统一

### ISSUE THREAD

**Issue by Developmc** [cryptokylin/KylinDappSpec#5]
举个例子：**扫码登录** 的协议，2-Web JS SPEC.md中描述的二维码参数和4-APP Native SPEC.md描述的参数相差很远；同样的，对于**支付**和**执行合约**也同样存在参数差异，而且差异还比较大；
我认为**扫码登录**和**拉起APP登录**协议应该保持一致才是合理的，完全没必要区分对待。

**Comment by winlin** [comment]
感谢提醒，我已经做了一次统一，可以参看 https://github.com/cryptokylin/KylinDappSpec/pull/6
